### ISSUE TITLE
did you boot successfully?

### ISSUE THREAD

**Issue by Boom-Hacker** [anonymix007/android_device_nubia_nx729j#1]

**Comment by anonymix007** [comment]
![Screenshot_20240418-204945_Settings](https://github.com/anonymix007/android_device_nubia_nx729j/assets/48598263/9583ed20-a155-4129-8f1b-26bce2fa534e)

**Comment by Boom-Hacker** [comment]
thanks.btw,when i can boot it(since which commit?)

**Comment by anonymix007** [comment]
AFAIR it first booted after 237fbf7ea90165f0b05b70c2498fa0a01f0bdb99
